-- MySQL Script generated by MySQL Workbench
-- Tue Nov  5 21:22:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema p4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p4` DEFAULT CHARACTER SET utf8 ;
USE `p4` ;

-- -----------------------------------------------------
-- Table `p4`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p4`.`professor` (
  `PNum` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PNum`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `p4`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p4`.`student` (
  `SNum` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  `professor_PNum` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`SNum`),
  INDEX `fk_student_professor_idx` (`professor_PNum` ASC) VISIBLE,
  CONSTRAINT `fk_student_professor`
    FOREIGN KEY (`professor_PNum`)
    REFERENCES `p4`.`professor` (`PNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
